### ISSUE TITLE
Browsersupport Rijksoverheid

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#59]
## Definition of done
- [ ] Supporten van de volgende browsers is wat Rijksoverheid voorschrijft https://www.communicatierijk.nl/vakkennis/rijkswebsites/aanbevolen-richtlijnen/browsersupport 

## Todo:
- [X] IE11 test *(why not IE10? well IE10 doesn't by default support TLS1.2+ and TLS1.0/1.1 is deprecated, although you can manually enable it on IE 10 I still think if we deploy to a TLS1.2+ server, IE10 testing is kind of useless)*
- [ ] Edge test
- [ ] Safari test
- [ ] iPad test
- [X] iPhone test
- [ ] Android Chrome test
- [ ] other Android browser tests
- [X] [lynx](https://en.wikipedia.org/wiki/Lynx_(web_browser)) :wink: (also to get a good A11Y/screenreader feeling!)

## Help wanted
Can someone run the site through http://browsershots.org/ or similar and suggest pull requests where necessary?
